# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceBlackBelt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
