# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceBlackBelt', '0002_bookmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookManager',
        ),
    ]
